export const CREATE_PROJECT = "CREATE_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const SET_SELECTED_PROJECT = "SET_SELECTED_PROJECT";
export const REMOVE_SELECTED_PROJECT = "REMOVE_SELECTED_PROJECT";
